# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# Use cargo to test the project
test:fmt:
  script:
    - rustup default nightly
    - rustup component add rustfmt
    - rustup update
    - rustup --version && rustc --version && cargo --version
    - cargo fmt --all -- --check

test:test:
  script:
    - rustup default nightly
    - rustup update
    - rustup --version && rustc --version && cargo --version
    - cargo test --all --verbose

test:bench:
  script:
    - rustup default nightly
    - rustup update
    - rustup --version && rustc --version && cargo --version
    - cargo bench --all --verbose
